"""add_onboarding_fields_to_user

Revision ID: 0007
Revises: 0006
Create Date: 2026-06-03 20:07:12.662442

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0007"
down_revision: Union[str, Sequence[str], None] = "0006"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("name", sa.String(), nullable=False, server_default="")
    )
    op.add_column(
        "users",
        sa.Column(
            "phone_number", sa.String(), nullable=False, server_default="0000000000"
        ),
    )
    op.add_column(
        "users",
        sa.Column("enrollment_number", sa.String(), nullable=False, server_default=""),
    )
    op.add_column(
        "users",
        sa.Column("is_onboarded", sa.Boolean(), nullable=False, server_default="false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_onboarded")
    op.drop_column("users", "enrollment_number")
    op.drop_column("users", "phone_number")
    op.drop_column("users", "name")
    # ### end Alembic commands ###
